version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-pista
    environment:
      MYSQL_ROOT_PASSWORD: ff65@Abindini
      MYSQL_DATABASE: pista
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
